#!/usr/bin/env python

import rospy

from asistente_usuarios import gen_ruta_code

def inicia_nodo():
    try:
        rospy.init_node("gen_ruta_node")
        turtlebot3 = gen_ruta_code.Ruta()
        turtlebot3.ejec_ruta()

    except rospy.ROSInterruptException:
        rospy.logerr("O presionaste CTRL+C o algo salio mal...")


if __name__ == "__main__":
    inicia_nodo()